name: Build newsletter JSON

on:
  push:
    paths:
      - 'newsletters/**'
      - 'scripts/**'
      - '.github/workflows/build-newsletter-json.yml'

permissions:
  contents: write   # ← Actions가 json을 커밋하려면 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate JSON
        run: ./node scripts/generate.js

      - name: Commit & Push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add newsletterData.json
            git commit -m "chore: update newsletterData.json"
            git push
          else
            echo "No changes to commit"
          fi
